### ISSUE TITLE
[Question] Are there any simple ways to get a binary data of NSData or NSInlineData?

### ISSUE THREAD

**Issue by y-ich** [TooTallNate/NodObjC#102]
Hi, thank you for your nice library.

I got an image data as NSInlineData via NodObjC.
Since I could not find a simple way to convert it into a Buffer object in the document and sources, I converted it from the result of toString() or 'description'.

If you already provided a right way, please let me know.
Thanks.

**Comment by lukaskollmer** [comment]
What about [`-[NSData bytes]`](https://developer.apple.com/documentation/foundation/nsdata/1410616-bytes?language=objc)? 
That returns `const char*`, from which you could create a `Buffer`

**Comment by y-ich** [comment]
I tried 'bytes' but the return value was an empty instance of Buffer...

**Comment by TooTallNate** [comment]
I think it's something like `const buffer = ref.reinterpret(data('bytes'), data('length'));`

**Comment by y-ich** [comment]
It works! Thank you!
