### ISSUE TITLE
TypeError: error setting argument 0 - writePointer: Buffer instance expected as third argument

### ISSUE THREAD

**Issue by Loknar** [TooTallNate/NodObjC#48]
I've been messing around with your module a little bit recently (very cool module btw), I threw together a simple module, [macmouse](https://github.com/Loknar/node-macmouse/), that gives you the ability to control your mouse through node.js, now I'm trying to fetch information on open windows via `CGWindowListCopyWindowInfo` (the idea is to do something fun using that information and the virtual mouse functionality).
I don't have much experience with Objective C but I stumbled upon an example of this in a blog post: http://b2cloud.com.au/tutorial/monitoring-any-window-in-os-x/
I tested it out in Xcode,

```
#import "Foundation/Foundation.h"
#import "Cocoa/Cocoa.h"

NSArray* windows = CFBridgingRelease(CGWindowListCopyWindowInfo(kCGWindowListOptionAll, kCGNullWindowID));
NSLog(@"%@", windows);
```

and it prints out all the data I want and more, but now I'm stuck on how to do this using the NodObjC module.

Here's my go at it (using NodObjC v1.0.0):

```
var $ = require('NodObjC');
$.framework('Foundation');
$.framework('Cocoa');
var pool = $.NSAutoreleasePool('alloc')('init');

var windowList = $.CFBridgingRelease($.CGWindowListCopyWindowInfo($.kCGWindowListOptionAll, $.kCGNullWindowID));

console.log(windowList);

pool('drain');
```

but I'm getting the following error:

```
/Users/loknar/Desktop/nodobjc_stuff/node_modules/ffi/lib/_foreign_function.js:55
      throw e
            ^
TypeError: error setting argument 0 - writePointer: Buffer instance expected as third argument
    at Object.writePointer (/Users/loknar/Desktop/nodobjc_stuff/node_modules/ffi/node_modules/ref/lib/ref.js:740:11)
    at Object.set (/Users/loknar/Desktop/nodobjc_stuff/node_modules/ffi/node_modules/ref/lib/ref.js:482:13)
    at Object.alloc (/Users/loknar/Desktop/nodobjc_stuff/node_modules/ffi/node_modules/ref/lib/ref.js:514:13)
    at ForeignFunction.proxy (/Users/loknar/Desktop/node_robot/nodobjc_stuff/ffi/lib/_foreign_function.js:50:22)
    at Function.unwrapper (/Users/loknar/Desktop/nodobjc_stuff/node_modules/NodObjC/lib/core.js:297:31)
    at Object.<anonymous> (/Users/loknar/Desktop/nodobjc_stuff/listOfWindows.js:44:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Any suggestions, tips or comments are very much appreciated.

edit:
question posted on [stackoverflow](http://stackoverflow.com/questions/25595194/getting-window-location-of-open-apps-via-nodobjc).

**Comment by nomeyer** [comment]
Hey there,

Thanks for this package. Looks quite powerful and a good addition to electron.

I just spent a while trying to figure out how to make Objective-C's toll-free bridging work. (Specifically, I was looking at https://developer.apple.com/library/mac/documentation/ApplicationServices/Reference/AXUIElement_header_reference/index.html#//apple_ref/c/func/AXUIElementCopyAttributeNames and other `AXUIElement` functions).

> You should use $.alloc($.CLASSSNAME).ref() to get a uninitialized, but allocated error pointer to pass into the function.

It would be great if this was mentioned somewhere in the documentation. For future Googlers – to get a `CFArrayRef`, write `var arrayRef = $.alloc($.NSArray).ref();`.

Thanks!

**Comment by ghost** [comment]
So we can use `$.alloc($.CLASSSNAME).ref()` to get an "uninitialized, but allocated error pointer". How does one go about creating a pointer that is initialised to a value?

If I understand correctly:  
`NSError * error;` ===  `$.alloc($.NSError).ref()` 

How can we do:
`NSError * error = nil;` === `???`

This is necessary because there are some ObjC functions (or bugs) that require it to be initialised to `NIL`, and I'm running into these very issues ([see here](http://mikeabdullah.net/nsurl-bookmark-error-handling.html) and [here](http://www.bornsleepy.com/2012/10/05/nserror-and-paranoia.html)).

**Comment by ghost** [comment]
I believe I figured it out, if I'm right, for future readers:

`NSError * error = nil` should be `$.alloc($.NSError, $.NIL).ref()`
