### ISSUE TITLE
Support for "Block" Functions.

### ISSUE THREAD

**Issue by TooTallNate** [TooTallNate/NodObjC#5]
Being able to call any function/method that accepts a "Block" parameter should be able to work with a regular JS Function. I just need to figure out how to go from a function pointer to a Block pointer at runtime.

This might be related: http://clang.llvm.org/docs/Block-ABI-Apple.txt

Example (currently segfaults):

``` javascript
var $ = require('NodObjC')
$.import('Foundation')
$.NSAutoreleasePool('alloc')('init')

// Create an NSArray with some random entries
var array = $.NSMutableArray('alloc')('init')
for (var i = 0; i<10; i++) {
  var str = $._(String.fromCharCode(Math.round(Math.random()*26)+('a'.charCodeAt(0))))
  array('addObject', str)
}

// Enumerate using a Block
array('enumerateObjectsUsingBlock', function (obj, index, stopPtr) {
  console.log('%d: %s', index, obj)
})
```

**Comment by ghost** [comment]
Can anyone help me understand what the array is that we're passing as the second argument to the block?

For example, in `test/block.js` the second argument after the function itself is: `['v',['?', '@','I','^B']]`.

```javascript
// Enumerate using a Block
array('enumerateObjectsUsingBlock', $(function (self, obj, index, bool) {
	var d = array('objectAtIndex',index)('description')('UTF8String');
	var v = obj('description')('UTF8String');
	assert.equal(d,v);
}, ['v',['?', '@','I','^B']]));
```
