### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by baloi91** [TooTallNate/NodObjC#55]
Hi all,
I'm new to nodejs and I'm trying to build an app that include NodObjC and I have a problem when package my app.
I did an "sudo npm install NodObjC" on my workspace, every things seems to work ok. But when I copy the source (include node-modules/NodObjC folder) for packaging, my app crash:

17:28:33.185 ERROR: "CRASH: ", "Module did not self-register."
17:28:33.186 ERROR: "Backtrace:"
17:28:33.186 ERROR: "Error: Module did not self-register."
17:28:33.186 ERROR: "    at Error (native)"
17:28:33.186 ERROR: "    at Module.load (module.js:354:32)"
17:28:33.186 ERROR: "    at Function.Module._load (module.js:310:12)"
17:28:33.186 ERROR: "    at Module.require (module.js:362:17)"
17:28:33.186 ERROR: "    at require (module.js:378:17)"
17:28:33.186 ERROR: "    at bindings (/node_modules/NodObjC/node_modules/ref/node_modules/bindings/bindings.js:76:44)"
17:28:33.187 ERROR: "    at Object.<anonymous> (/node_modules/NodObjC/node_modules/ref/lib/ref.js:5:47)"
17:28:33.187 ERROR: "    at Module._compile (module.js:454:26)"
17:28:33.187 ERROR: "    at Object.Module._extensions..js (module.js:472:10)"
17:28:33.187 ERROR: "    at Module.load (module.js:354:32)"

Any help would be appriciated!

**Comment by TooTallNate** [comment]
If you're moving the compiled binary to a different computer than you'll most likely need to recompile the binary.
