### ISSUE TITLE
hello! how to use ffi moudle link a dll file?

### ISSUE THREAD

**Issue by Einsy** [TooTallNate/NodObjC#57]
typedef struct _LogInfo
{
	char severip[16];
	int  severport;
	char severid[24];
	char localip[16];
	int  localport;
	char username[24];
	char password[64];
	int  keepalive;
	int  timeout;
	int  expires;
}LogInfo;

typedef void (*Callback_Offline)( void *userdata );

int GBAPI NP_GB_Login( void* userdata, LogInfo &info, Callback_Offline callback );

My nodejs code is:

var SDKHandle = ffi.Library('./gbsdk-console', {
	'NP_GB_Init': ['void', []],
	'NP_GB_Login': ['int', ['void',_LogInfoPtr,voidptr]]
});

var logInfo= new Buffer(164);
logInfo.write("192.168.60.107\0\0",0,16);
logInfo.writeInt32LE(5060,16);
logInfo.write("15000000002000000001\0\0\0\0",20,24);
logInfo.write("192.168.60.46\0\0",44,16);
logInfo.writeInt32LE(81,60);
logInfo.write("15000000004000000003\0\0\0\0",64,24);
logInfo.write("123456\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",88,64);
logInfo.writeInt32LE(60,152);
logInfo.writeInt32LE(3,156);
logInfo.writeInt32LE(3600,160);

SDKHandle.NP_GB_Init();

var N=SDKHandle.NP_GB_Login("null",logInfo,Callback_Offline);
console.log(N);

NP_GB_Login is all right, but the callback is not run!

I wang  get  the answer,thanks!

**Comment by Einsy** [comment]
in addition to the up,

var ffi = require('ffi');
var ref = require('ref');
var Struct = require('ref-struct');
//var hWnd = new Buffer(8);
var int64_t = ref.types.int64;
var voidptr = ref.refType(ref.types.void);
var intptr = ref.refType(ref.types.int);
var uint8_ptr = ref.refType(ref.types.uint8);

**Comment by TooTallNate** [comment]
Maybe this belongs in `node-ffi` repo? https://github.com/node-ffi/node-ffi/issues
