### ISSUE TITLE
Problem regarding this package on npmjs.com

### ISSUE THREAD

**Issue by Loknar** [TooTallNate/NodObjC#92]
https://www.npmjs.com/package/nodobjc (currently version 2.1.0)
vs
https://www.npmjs.com/package/NodObjC (currently version 1.0.0)

and the latter comes up when searching for "nodobjc"

**Comment by TooTallNate** [comment]
The package name with uppercase letter (`NodObjC`) is deprecated and will no longer be updated. If you try to `npm install NodObjC`, you will be greeted with a deprecation warning. The lowercase `nodobjc` is now preferred.
