### ISSUE TITLE
Mac App Store?

### ISSUE THREAD

**Issue by ghost** [TooTallNate/NodObjC#94]
Just a quick question, I'm thinking of using this inside an [`electron`](https://github.com/electron/electron) application, but I'm planning on building and releasing inside the sandbox for the Mac App Store. 

I want to use it so I can register some Security-Scoped bookmarks (functionality that's not within `electron` at the moment.

Do you think this will be rejected by the Mac App Store review ? Or is all this dynamic linking perfectly fine?

... In any case I'll comment here if it passes ...

**Comment by darkyen** [comment]
Did it pass?

**Comment by callodacity** [comment]
@darkyen I never got around to publishing that app. I ended up going down another route, and didn't end up using electron anyway.

**Comment by ghost** [comment]
@darkyen Sorry it took so long!

I managed to use `nodobjc` to create [`electron-bookmarks`](https://www.npmjs.com/package/electron-bookmarks) which I used in a electron-based app. And it's just passed the review! 👍
