### ISSUE TITLE
NSTouchBar usage

### ISSUE THREAD

**Issue by rgascons** [TooTallNate/NodObjC#98]
Hello,

I'm attempting to build a NodeJS wrapper for NSTouchBar classes and I'm planning on using NodObjC for the bindings.

However, I'm not succeeding on using even the base class of the library. This is a sample code of what I'm attempting:

```javascript
const $ = require('nodobjc')

$.framework('Foundation')
$.framework('Cocoa')

let pool = $.NSAutoreleasePool('alloc')('init')
let touchbar = $.NSTouchBar()
```

But the last line fails to execute, throwing the following error: `Selector passed in was empty.`

Any clues about what I'm doing wrong? I can provide more info if necessary.

Thank you.

**Comment by lukaskollmer** [comment]
```js
let touchbar = $.NSTouchBar('new');
```
